[package]
name = "chap016"
version = "0.1.0"
authors = ["WATANAPEI <info@wpei.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chap015 = { path = "../chap015" }
